export const FETCH_HOTELS = "FETCH_HOTELS";
export const UPDATE_SEARCH = "UPDATE_SEARCH";
export const FETCH_HOTELS_ERROR = "FETCH_HOTELS_ERROR";
export const FETCH_WEATHER = "FETCH_WEATHER";
export const FETCH_WEATHER_ERROR = "FETCH_WEATHER";
export const SET_LOADING = "SET_LOADING";
